name: Welcome New Contributor

permissions:
  issues: write
  contents: read

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Comentar bienvenida
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const creator = context.payload.issue.user.login;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `¡Hola @${creator}! Gracias por tu contribución a esta master class. Nuestro equipo revisará tu issue pronto. 🚀`
            });

      - name: Publicar mini-tutorial de Actions
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `
**¿Quieres ver cómo funciona esta Action?**  
1. Cada vez que creas un issue, se dispara este flujo.  
2. El paso **Comentar bienvenida** usa \`github-script\` para invocar la API y dejar un comment.  
3. Ahora mismo estoy añadiendo este comentario como **PASO ADICIONAL**, demostrando cómo encadenar múltiples comentarios.

_— Explora \`.github/workflows/welcome.yml\` y verás los pasos definidos bajo \`jobs.welcome.steps\`._
              `
            });
