name: Welcome New Contributor

permissions:
  issues: write
  contents: read

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Debug context.issue
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Issue payload:", JSON.stringify(context.payload.issue, null, 2));

      - name: Comentar bienvenida
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const creator = context.payload.issue.user.login;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `¡Hola @${creator}! Gracias por tu contribución, en breve revisamos. 🚀`
            });

      - name: Publicar mini-tutorial
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `**¿Cómo funciona?**  
- Este flujo corre al crear un issue.  
- Paso 1: debug del payload.  
- Paso 2: comentario de bienvenida.  
- Paso 3: este mini-tutorial.`
            });
